version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "meteor",
    "vue",
    "angular"
  ]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/venkatreddyc/CloudCosts"